---

- name: Get upstream APT GPG key
  apt_key:
    id: '{{ docker_upstream_key }}'
    keyserver: '{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver)
                   else "hkp://pool.sks-keyservers.net" }}'
    state: 'present'
  when: docker_upstream|d() | bool

- name: Configure upstream APT repository
  apt_repository:
    repo: '{{ docker_upstream_repository }}'
    state: 'present'
    update_cache: True
  when: docker_upstream|d() | bool

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: 'present'
    install_recommends: False
  with_flattened:
    - [ '{{ "docker-engine" if docker_upstream|d() else "docker.io" }}' ]
    - docker_base_packages
    - docker_packages

- name: Install pip
  apt:
    name: python-pip
    state: 'present'
    install_recommends: False

- name: Install ferment generator
  pip:
    name: 'ferment'
    state: 'present'
  when: docker_ferment|d() | bool

- name: Install ferment wrapper script
  template:
    src: 'usr/local/lib/docker-ferment-wrapper.j2'
    dest: '{{ docker_ferment_wrapper }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: docker_ferment|d() | bool

- name: Check Docker version
  environment:
    LC_MESSAGES: 'C'
  shell: dpkg-query -W -f='${Version}\n' '{{ ("docker-engine" if docker_upstream|d() else "docker.io") }}' | cut -d- -f1
  register: docker_register_version
  changed_when: False
  failed_when: False
  tags: [ 'role::docker:config' ]

- name: Configure Docker options
  template:
    src: 'etc/default/docker.j2'
    dest: '/etc/default/docker'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart docker' ]
  tags: [ 'role::docker:config' ]

- name: Install Debian systemd service unit
  template:
    src: 'etc/systemd/system/docker.service.j2'
    dest: '/etc/systemd/system/docker.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Restart docker' ]
  register: docker_register_systemd_service
  when: docker_upstream|d() | bool
  tags: [ 'role::docker:config' ]

- name: Reload systemd daemons
  command: systemctl daemon-reload
  when: ((ansible_local|d() and ansible_local.init|d() and
          ansible_local.init == 'systemd') and
         docker_register_systemd_service|d() and
         docker_register_systemd_service.changed)
  tags: [ 'role::docker:config' ]

- name: Add specified users to 'docker' group
  user:
    name: '{{ item }}'
    groups: 'docker'
    append: True
  with_items: docker_admins
  when: item|d()
  tags: [ 'role::docker:config', 'role::docker:admins' ]

